#!/bin/bash
# Upload all scripts and sync to RouterOS

ROUTER_IP="192.168.88.1"
ROUTER_USER="admin"
SSH_KEY="$HOME/.ssh/id_rsa_routeros"
RSC_FILE="import_scripts.rsc"

# Require router-specific SSH key
if [ ! -f "$SSH_KEY" ]; then
    echo "Error: SSH key not found at $SSH_KEY"
    echo "Run ./setup-ssh-keys.sh to generate the key"
    exit 1
fi

SSH_OPTS="-i $SSH_KEY -o PasswordAuthentication=no"

# Generate .rsc import file
echo "Generating import file..."

# Get git commit hash and dirty status
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if [ -z "$(git status --porcelain 2>/dev/null)" ]; then
    GIT_STATUS="$GIT_HASH"
else
    GIT_STATUS="$GIT_HASH-dirty"
fi

# Get current date with timezone offset
GEN_DATE=$(date '+%Y-%m-%d %H:%M:%S %z')

# Write header
cat > "$RSC_FILE" << RSC_HEADER
# RouterOS script import file
# Generated by sync-script.sh
# Date: $GEN_DATE
# Git: $GIT_STATUS

RSC_HEADER

# Write header for creating scripts section
printf ':put "=== Creating scripts ==="\n' >> "$RSC_FILE"
printf '\n' >> "$RSC_FILE"

# Create function for script creation
printf ':global createScriptIfMissing do={\n' >> "$RSC_FILE"
printf '    :if ([/system script print count-only where name=$scriptName] = 0) do={\n' >> "$RSC_FILE"
printf '        :put ("Creating script: " . $scriptName);\n' >> "$RSC_FILE"
printf '        /system script add name=$scriptName\n' >> "$RSC_FILE"
printf '    }\n' >> "$RSC_FILE"
printf '}\n\n' >> "$RSC_FILE"

# Write all add commands first
for SCRIPT_FILE in scripts/config/*.rsc scripts/check/*.rsc; do
    if [ ! -f "$SCRIPT_FILE" ]; then
        continue
    fi
    
    SCRIPT_NAME=$(sed -n '1p' "$SCRIPT_FILE" | sed 's/^# //')
    POLICY=$(sed -n '3p' "$SCRIPT_FILE" | sed -n 's/^# policy=\(.*\)/\1/p')
    
    if [ -z "$POLICY" ]; then
        echo "Error: Missing policy in $SCRIPT_FILE (line 3 should be '# policy=read,write')"
        exit 1
    fi
    
    # Call function with script name
    printf '$createScriptIfMissing scriptName="%s"\n' "$SCRIPT_NAME" >> "$RSC_FILE"
done

# Empty line between sections
printf '\n' >> "$RSC_FILE"
printf ':put ""\n' >> "$RSC_FILE"
printf ':put "=== Updating scripts ==="\n' >> "$RSC_FILE"
printf '\n' >> "$RSC_FILE"

# Write all set commands
for SCRIPT_FILE in scripts/config/*.rsc scripts/check/*.rsc; do
    if [ ! -f "$SCRIPT_FILE" ]; then
        continue
    fi
    
    SCRIPT_NAME=$(sed -n '1p' "$SCRIPT_FILE" | sed 's/^# //')
    COMMENT=$(sed -n '2p' "$SCRIPT_FILE" | sed 's/^# //')
    POLICY=$(sed -n '3p' "$SCRIPT_FILE" | sed -n 's/^# policy=\(.*\)/\1/p')
    
    # Escape comment for RouterOS (escape quotes)
    ESCAPED_COMMENT=$(echo "$COMMENT" | sed 's/"/\\"/g')
    
    # Read script content and escape for RouterOS .rsc format
    # Loop through file line by line, escape special chars, join with \n
    SCRIPT_CONTENT=""
    while IFS= read -r line || [ -n "$line" ]; do
        # Escape backslashes, dollar signs, and quotes
        line=$(echo "$line" | sed 's/\\/\\\\/g' | sed 's/\$/\\$/g' | sed 's/"/\\"/g')
        if [ -z "$SCRIPT_CONTENT" ]; then
            SCRIPT_CONTENT="$line"
        else
            SCRIPT_CONTENT="$SCRIPT_CONTENT\\n$line"
        fi
    done < "$SCRIPT_FILE"
    
    # Write set command directly to file
    printf ':put "Updating script: %s"; /system script set "%s" source="' "$SCRIPT_NAME" "$SCRIPT_NAME" >> "$RSC_FILE"
    echo "$SCRIPT_CONTENT" | sed 's/\\n/\\n\\\n    /g' >> "$RSC_FILE"
    printf '" comment="%s" policy=%s\n\n' "$ESCAPED_COMMENT" "$POLICY" >> "$RSC_FILE"
done

# Delete the helper function
printf '\n:set createScriptIfMissing;\n' >> "$RSC_FILE"

# Print all scripts (excluding source/contents)
printf ':put ""\n:put "=== All system scripts ==="\n/system script print proplist=name,comment,owner,policy,dont-require-permissions,run-count,last-started,invalid\n' >> "$RSC_FILE"

# Show generated .rsc file and ask for confirmation
echo ""
echo "=== Generated import file ($RSC_FILE) ==="
head -20 "$RSC_FILE"
echo "..."
echo ""
read -p "Upload and import this file? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted"
    rm -f "$RSC_FILE"
    exit 1
fi

# Upload .rsc file
echo "Uploading import file..."
scp $SSH_OPTS "$RSC_FILE" "$ROUTER_USER@$ROUTER_IP":/

# Import on router
echo "Importing scripts..."
ssh $SSH_OPTS "$ROUTER_USER@$ROUTER_IP" "/import file-name=$RSC_FILE"

# Cleanup
rm -f "$RSC_FILE"
echo "Done!"
